### ISSUE TITLE
Tree misbehaving in several ways.

### ISSUE THREAD

**Issue by mk23** [ExactTarget/fuelux#854] opened 2014-11-18 08:01 UTC
I have an example with some contrived data here:  http://jsfiddle.net/kvbqnc29/5/

1. On _Safari 8.0_, selecting a leaf node changes the icons of the parents.  To reproduce the problem, open `Top Level Tree 2` and select either of the Leaf children.
1. On _Safari 8.0_, opening a folder fires the `selected.fu.tree` event.
1. On _FireFox 33.1.1_, opening folders doesn't work at all.

I am expecting that this is user error, and would love a pointer to support this theory.

**Comment by mbeard** [comment] 2015-02-10 20:08
Was anyone able to reproduce this?  I was not able to.

**Comment by swilliamset** [comment] 2015-02-10 22:54
also not able

**Comment by swilliamset** [comment] 2015-02-10 22:58
jsfiddle http://jsfiddle.net/kvbqnc29/5/ not working in firefox 35.0.1 but successful in safari 8.0.3

folder doesn't open in firefox

**Comment by cormacmccarthy** [comment] 2015-02-27 14:24
I seem to remember tree having had issues in jsfiddle in the past, so, here is a jsbin version of the same thing to rule out this being a jsfiddle issue: http://jsbin.com/neledeyanu/1/

**Comment by swilliamset** [comment] 2015-02-27 18:41
@cormacmccarthy to provide more info on monday

**Comment by interactivellama** [comment] 2015-05-22 19:24
@mk23 I think this is duplicate of the #1283 and should not be fixed. Selecting an item was causing folder icons to be changed due to the $.find() cascade.

**Closed by interactivellama** 2015-05-22 19:24 UTC
Labels: Confirmed bug, tree
